### ISSUE TITLE
Cannot rename file. Operation not permitted

### ISSUE THREAD

**Issue by MrMedusa** [pepzwee/node-csgo-web-tradebot#37]
### Expected behavior
No clue, I guess it just has to save the new cookies etc.

### Actual behavior
Gives me an error

### Steps to reproduce the behavior
I have no clue

### Other
1. [Operating System]: Windows 10 Pro
2. [Node.js version]: Version. 6.10.2
3. [How did you start the script]: node index.js

I did some looking around, but I found no fix.
This basically means I cannot login to the site.

### Error Stack
```
Error: EPERM: operation not permitted, rename 'C:\Users\Gandalf\Desktop\Trade Site\sessions\Session_String.json.123456' -> 'C:\Users\Gandalf\Desktop\Trade Site\sessions\Session_String.json'
    at Error (native)
```

**Comment by Dakshster** [comment]
Okay, Which version of node are you using?

Find out via `node -v` in command prompt.

**Comment by FreddyFish** [comment]
@Dakshster  > He is running 6.10.2

**Comment by MrMedusa** [comment]
Yea. I've done that twice. No clue why this is happening.

**Comment by Dakshster** [comment]
@MrMedusa @FreddyFish 
Okay, I submitted a PR which might fix it because your system is not allowing the storage of the session (FileStore), and that also makes it slow. So Why not use, Direct Express-sessions It's fast and Doesn't cause issues like these.
This also gives you additional choice, You can add Redis Store, Mongo Store, etc.

Fixed in https://github.com/pepzwee/node-csgo-web-tradebot/pull/38
