### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by hermanse** [pepzwee/node-csgo-web-tradebot#50]
Hi bros! Can you help me set up this script without steamapi.com ? I need upload inv on my bot and taking prices from csgofast. Pls, i dont't know js...
I need change inv.js and prices.js right? On what i need change it?

**Comment by Dev-rahul** [comment]
Hey can u help me set up the bot on a vps?

On 17-Jun-2017 8:47 PM, "hermanse" <notifications@github.com> wrote:

Hi bros! Can you help me set up this script without steamapi.com ? I need
upload inv on my bot and taking prices from csgofast. Pls, i dont't know
js...
I need change inv.js and prices.js right? On what i need change it?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pepzwee/node-csgo-web-tradebot/issues/50>, or mute the
thread

**Comment by FreddyFish** [comment]
I can help, add me on Stram. (Can be found on my github profile.)

**Comment by string-null** [comment]
me too
